project:
  type: website

website:
  title: ""
  site-url: "https://bailey-medics.com"
  navbar:
    logo: media/bm-logo-transparent.png
    left:
      - href: mark-bailey-cv.qmd
        text: Mark CV
      - href: mark-bio.qmd
        text: Mark's Bio
      - href: builds.qmd
        text: Previous builds
      - href: contact.qmd
        text: Contact

  favicon: media/bm-logo.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
