project:
  type: website

website:
  title: ""
  site-url: "https://bailey-medics.com"
  navbar:
    logo: media/bm-logo.png
    left:
      - href: mark-bailey.qmd
        text: Mark CV
      - href: builds.qmd
        text: Previous builds

    favicon: media/lbm-logo.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
