---
title: "Mark' Bio"
---

I have had quite a few people ask me how did I get to the point where I am in regards to clinical informatics, and so I thought I would write a quick biography on the topic.

I have always had an interest in all things digital. I played on my Dad’s Apple II computer as a young child, and then played on a range of gaming consoles growing up. I started playing with internet-of-things in 2014 on the Arduino plateform, and started to automated my house for fun. I also learnt about python and linux when I started building my own webpage as part of the home automation.

So, with this interest in automating things, basically to take over the boring and tedious tasks, I applied some of this digital knowledge at work. I was trained up to help run the sleep service at Gloucestershire Royal Hospital in April 2018 and was asked to help with the services back log. We had over 350 sleep studies to report and a large percentage of patients waiting over a year for treatment. So, I diligently went through the studies, but it was a very monotonous and boring task. After my first 50 sleep studies (it took some time due to other commitments), I thought there must be a better way of doing this. So in December 2018 I built a very basic Word document with macros that had some drop down lists that you would change for things like the severity of the patient’s condition and their weight, etc. Most of the sleep study reports were very similar apart for some slight changes between patients, so this new Word document work really well.

After a while, I thought the Word document could be improved further. So I build an Excel file with macros that allowed you to add several patients, and then one after another you could print off reports. This is when one of my supervisors asked if I could build a database to house the whole sleep service data and pathway, from referral to treatment. I had never worked on a database before, but I thought I would give it a try. So I looked for a free database solution and found that the trust had Microsoft Access 2010. So I bought myself Access 2010 and VBA for Dummies, read both books all the way through and over the course of 2019 build a new database for the sleep service.

The new database was a success. The whole sleep service (apart from follow ups) is run within this new database. By the way, the name of this database is Spiritum: this is Latin for ‘breath’.

So my supervisor asked if I could add tuberculosis and bronchiectasis to the Spiritum database, and so I did. At the same time I added functionality so that Spiritum could connect to other clinical systems and grab sleep studies, blood results, imaging reports, etc.

Some of the above functionality was carried out with robotic process automation (RPA). I started thinking, why not use RPA to speed up daily, routine clinical admin tasks. So I build a stand-alone RPA solution called Quick Spiritum. This connects to 9 clinicial systems, and showed a 30% reduction in the time to obtain results. It also can create and send referrals and requests for 4 diciplines. I have not studied the time savings with the latter functionality, but I would think it would be hours to days (as no need to hunt for paper request forms, send to the secretaries to then either fax, scan and email or post).

So now we are at the next stage of my digital journey. My supervisor has asked me to create a new lung cancer pathway. And that is the reason you are here in the first place.